### ISSUE TITLE
Solve 327A - Flipping Game

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/CP-Practice#11]
Problem Link - https://codeforces.com/problemset/problem/327/A
Problem rating: **1200**
Tag -   `brute force`    `dp`    `implementation`  
Platform - Codeforces
Diffculty - Easy

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

- Appropriate title of PR
- Making another branch with an appropriate name.
- Comment on file in the top with the link of the question

Happy Coding

**Comment by nishkarsh540** [comment]
@sagarmittal1  can I work on this issue?

**Comment by sagarmittal1** [comment]
Assigned it to you.

**Comment by nishkarsh540** [comment]
@sagarmittal1 can you check my work?
