### ISSUE TITLE
Solve 1154B - Make Them Equal (1200)

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/CP-Practice#12]
Problem Link - https://codeforces.com/contest/1154/problem/B
Problem rating: **1200**
Tag - `math`
Platform - Codeforces
Diffculty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

- Appropriate title of PR
- Making another branch with an appropriate name.
- Comment on file in the top with the link of the question

Happy Coding

**Comment by nishkarsh540** [comment]
@sagarmittal1 
I am good at python and c++.
So can I work on this issue?
