### ISSUE TITLE
Solve 1300A - Dreamoon and Ranking Collection

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/CP-Practice#15]
Problem Link - https://codeforces.com/problemset/problem/1579/E2
Problem rating: **900**
Tag - `greedy`, `implemanation`
Platform - Codeforces
Diffculty - Easy

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

- [x] - Appropriate title of PR
- [x] - Making another branch with an appropriate name.
- [x] - Comment on file in the top with the link of the question

Happy Coding 👍

**Comment by nishkarsh540** [comment]
@sagarmittal1  can I work on this issue?

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
