### ISSUE TITLE
Solve C - Neo-lexicographic Ordering (AtCoder)

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/CP-Practice#3]
Problem Link - https://atcoder.jp/contests/abc219/tasks/abc219_c
Platform - AtCoder
Tag - `greedy`, `data structure`
Diffculty - Easy

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

- Appropriate title of PR
- Making another branch with an appropriate name.
- Comment on file in the top with the link of the question

Happy Coding

**Comment by sgaurav37533** [comment]
@sagarmittal1 please assign me this issue

**Comment by sagarmittal1** [comment]
Assigning it to you. Start working on it. When ready make a PR.
