### ISSUE TITLE
Solve 1559C - Mocha and Hiking (1200)

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/CP-Practice#4]
Problem Link - https://codeforces.com/problemset/problem/1559/C
Problem rating: **1200**
Tag -   `combinatorics `   `greedy`    `math`
Platform - Codeforces
Diffculty - Intermediate

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension. AND in the same folder

Make sure this before making PR regarding it :

- Appropriate title of PR
- Making another branch with an appropriate name.
- Comment on file in the top with the link of the question

Happy Coding

**Comment by tom635** [comment]
Assign me this issue:

**Comment by aayush0331** [comment]
Hey @sagarmittal1 ,Can I work on this issue.
