### ISSUE TITLE
Solution for COINS - Bytelandian gold coins (CodeChef)

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/CP-Practice#5]
Problem Link - https://www.codechef.com/problems/COINS
Tag - `greedy`, `data structure`
Platform - CodeChef
Diffculty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension. AND in the same folder

Make sure this before making PR regarding it :

- Appropriate title of PR
- Making another branch with an appropriate name.
- Comment on file in the top with the link of the question

Happy Coding 👍

**Comment by aayush0331** [comment]
Hey @sagarmittal1 ,Can I work on this issue.

**Comment by sgaurav37533** [comment]
assign me this issue please @sagarmittal1

**Comment by sagarmittal1** [comment]
Hey @sgaurav37533, @aayush0331 mentioned this first so, I have to issue him. there are other issues you can get assigned or if he is unable to do it then you can get assigned.

**Comment by sgaurav37533** [comment]
@aayush0331 Please assign me this issue i am really in need of one

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
