### ISSUE TITLE
Solve Mancunian And Colored Tree (HackerEarth)

### ISSUE THREAD

**Issue by sagarmittal1** [sagarmittal1/CP-Practice#6]
Problem Link - https://www.hackerearth.com/practice/data-structures/trees/binary-and-nary-trees/practice-problems/algorithm/mancunian-and-colored-tree/
Tag - `tree`, `data structure`
Platform - HackerEarth
Diffculty - Medium

To make the PR make the file Problems folder & write the file name as a like 500A - New Year Transportation.cpp or just like that with the correct extension.

Make sure this before making PR regarding it :

- Appropriate title of PR
- Making another branch with an appropriate name.
- Comment on file in the top with the link of the question

Happy Coding

**Comment by Arpitgupta1014** [comment]
Hey @sagarmittal1 ,Can I work on this issue.

**Comment by sagarmittal1** [comment]
Assigning it to you

**Comment by navjotdadwal** [comment]
Sir please assign this issue to me

Why you should assign this to me?
i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234
So i can handle and solve this issue
